"""make category_id nullable on transactions

Revision ID: 713e58a27d56
Revises: b769a28e4501
Create Date: 2026-02-24 21:49:21.112925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '713e58a27d56'
down_revision: Union[str, None] = 'b769a28e4501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('period', sa.String(), nullable=False))
    op.add_column('budgets', sa.Column('limit_amount', sa.Float(), nullable=False))
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.drop_column('budgets', 'created_at')
    op.drop_column('budgets', 'month')
    op.drop_column('budgets', 'year')
    op.drop_column('budgets', 'amount')
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('is_essential', sa.Boolean(), nullable=True))
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    op.add_column('goals', sa.Column('title', sa.String(), nullable=False))
    op.add_column('goals', sa.Column('target_date', sa.Date(), nullable=False))
    op.add_column('goals', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('goals', sa.Column('type', sa.String(), nullable=True))
    op.add_column('goals', sa.Column('comfort_floor', sa.Float(), nullable=True))
    op.alter_column('goals', 'target_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('goals', 'current_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.drop_column('goals', 'created_at')
    op.drop_column('goals', 'name')
    op.drop_column('goals', 'deadline')
    op.add_column('transactions', sa.Column('direction', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('merchant', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('note', sa.String(), nullable=True))
    op.alter_column('transactions', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.drop_column('transactions', 'description')
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'password_hash')
    op.add_column('transactions', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'note')
    op.drop_column('transactions', 'merchant')
    op.drop_column('transactions', 'direction')
    op.add_column('goals', sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('goals', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('goals', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.alter_column('goals', 'current_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('goals', 'target_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('goals', 'comfort_floor')
    op.drop_column('goals', 'type')
    op.drop_column('goals', 'priority')
    op.drop_column('goals', 'target_date')
    op.drop_column('goals', 'title')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    op.drop_column('categories', 'is_essential')
    op.drop_column('categories', 'user_id')
    op.add_column('budgets', sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_column('budgets', 'limit_amount')
    op.drop_column('budgets', 'period')
    # ### end Alembic commands ###
